version: '3.8'

services:
  web:
    build: .
    ports:
      - "${DEFAULT_FLASK_PORT}:${DEFAULT_FLASK_PORT}"
    env_file:
      - ./env/postgres.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data: